### ISSUE TITLE
RuntimeError: shape '[0, 3, 1, 2]' is invalid for input of size 1572864

### ISSUE THREAD

**Issue by dengfenglai321** [donahowe/AutoStudio#10]
生成图像报错如下！！

│                                                                                                  │
│ /xxx/workpace/AIGC/AutoStudio/DETECT_SAM/efficient_sam.py:31 in inference_with_box   │
│                                                                                                  │
│   28 │   bbox_labels = torch.reshape(torch.tensor([2, 3]), [1, 1, 2])                            │
│   29 │   img_tensor = ToTensor()(image)                                                          │
│   30 │                                                                                           │
│ ❱ 31 │   predicted_logits, predicted_iou = model(                                                │
│   32 │   │   img_tensor[None, ...].to(device),                                                   │
│   33 │   │   bbox.to(device),                                                                    │
│   34 │   │   bbox_labels.to(device),                                                             │
│                                                                                                  │
│ /xxx/anaconda/envs/th23/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 │
│ in _call_impl                                                                                    │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: shape '[0, 3, 1, 2]' is invalid for input of size 1572864

**Comment by donahowe** [comment]
This is typically an issue with the configuration of the SAM environment for the detection model.

**Comment by donahowe** [comment]
Hello, I have fixed the bug. Please clone the repository again and configure the environment. Thank you for your attention.
