### ISSUE TITLE
论文Table2中的TheaterGen比较结果

### ISSUE THREAD

**Issue by JoshonSmith** [donahowe/AutoStudio#18]
TheaterGen论文是基于sd1-5，但是本文Table2的TheaterGen有sdxl版本的结果，
请问这个结果是怎么得到的

**Comment by donahowe** [comment]
你好，TheaterGen拥有sd-1.5和sdxl两个版本，论文中的图使用sdxl版本绘制，而漫画风格的对比图统一采用基于sd1.5的漫画节点绘制
