### ISSUE TITLE
TypeError: StableDiffusionXLPipeline.__call__() got an unexpected keyword argument 'repeat_ind'

### ISSUE THREAD

**Issue by dengfenglai321** [donahowe/AutoStudio#19]
**使用XL**

更新代码后运行run.py报错如下

TypeError: StableDiffusionXLPipeline.__call__() got an unexpected keyword argument 'repeat_ind'

去掉这个参数正常运行， 生成结果有问题，纯黑色

boxes：
![boxes](https://github.com/donahowe/AutoStudio/assets/50360389/cdeeb523-14eb-477a-9f15-92a4a5802249)

img0_25step:
![img0_25step](https://github.com/donahowe/AutoStudio/assets/50360389/fd8d376b-f480-4d7e-897f-e8549832fc59)

**Comment by donahowe** [comment]
I see, it is fixed. However, I recommand fine-tuned sd-1.5 and SDXL checkpoints, for the base version is not very stable.

**Comment by dengfenglai321** [comment]
> I see, it is fixed. However, I recommand fine-tuned sd-1.5 and SDXL checkpoints, for the base version is not very stable.

请问怎么解决呢，出图是纯黑色。使用的是XL模型，， 1.5没有这个问题

**Comment by milely** [comment]
相同的问题，sdxl模型，出图纯黑色，请问怎么解决的这个问题呢
