### ISSUE TITLE
specific directory rely issue

### ISSUE THREAD

**Issue by PeakLee** [donahowe/AutoStudio#21]
<img width="1500" alt="image" src="https://github.com/donahowe/AutoStudio/assets/1582487/abfd49f0-10a8-47f8-b8f2-6bdebb80b45a">

/data2/chengjunhao/THEATERGEN/pretrained_models/dino_bert 

could help to update the project？？？

**Comment by PeakLee** [comment]
@donahowe

**Comment by donahowe** [comment]
I see, it is fixed. However, I recommand fine-tuned sd-1.5 and SDXL checkpoints, for the base version is not very stable.

**Comment by PeakLee** [comment]
thanks
