### ISSUE TITLE
模型配置

### ISSUE THREAD

**Issue by ShAw7ock** [donahowe/AutoStudio#26]
由于是SD这方面的新手，在模型配置方面有点疑惑，想请教一下本地Pretrained模型的配置问题

1. `StableDiffusion`模型按照推荐下载了[dreamlike-anime-1.0](https://huggingface.co/dreamlike-art/dreamlike-anime-1.0)
2. `IP-Adaptor` [下载](https://huggingface.co/h94/IP-Adapter)
3. `efficient_sam_s_gpu.jit` [下载](https://huggingface.co/spaces/SkalskiP/YOLO-World/tree/main)
4. 使用wget下载了`groundingdino_swint_ogc.pth`
5. 运行过程中自动从Huggingface下载了`bert-base-uncased`

在`run.py`脚本中：
1. `sd_path`配置了dreamlike-anime-1.0的文件夹路径
2. `vae_path`我也使用了dreamlike-anime-1.0/vae文件夹路径
3. `unet`我也使用了dreamlike-anime-1.0/unet文件夹路径
4. `ip_ckpt`和`image_encoder_path`用了`1.5plus`的版本

RTX 4090/24GB CUDA 11.8

不知道这样的配置会不会有什么问题，因为输出效果很差，完全无法复现repo和论文中提到的效果

**Comment by donahowe** [comment]
大概率是UNet没配置对不能用Base要用新的节点的UNet，还有VAE要单独下一个
