### ISSUE TITLE
Question about evaluation metric aCCS in paper

### ISSUE THREAD

**Issue by Exuan148** [donahowe/AutoStudio#27]
Hi, I would like to ask that what is the average character-character similarity (aCCS) metric mentioned in your paper, I cannot find its information on the internet. I'm looking forward to your reply, thanks!

**Comment by donahowe** [comment]
Hello, this is derived from CMIGBench proposed in TheaterGen. For more details, please refer to "TheaterGen: Character Management with LLM for Consistent Multi-turn Image Generation"
