### ISSUE TITLE
可否提供以下安装步骤的说明 ，谢谢

### ISSUE THREAD

**Issue by MillerYkk** [donahowe/AutoStudio#32]
可否提供以下安装步骤的说明 ，谢谢

Prepare /DETECT_SAMefficient_sam_s_gpu.jit and /DETECT_SAM/Grounding-DINO/groundingdino_swint_ogc.pth for groundingdino and efficientSAM

**Comment by fengyinhuaxu** [comment]
前者是在本地部署中就有的，查找一下就能找到，后者我就不知道了，确实是亟需作者提供这俩的安装方式

**Comment by donahowe** [comment]
在groundingdino官方库可下载
