### ISSUE TITLE
您好，复现的时候遇到了些问题

### ISSUE THREAD

**Issue by LORDPQK** [donahowe/AutoStudio#36]
大佬，微信群过期了呢，麻烦更新一下群呢

**Comment by LORDPQK** [comment]
![image](https://github.com/user-attachments/assets/b55c028e-839e-4c4d-91e4-fd14c2e8219d)

**Comment by LORDPQK** [comment]
论文中提到的P-UNet的代码在什么部分呢？

**Comment by donahowe** [comment]
P-Unet与Unet不同的部分可以在attention.py中的AutoStudioAttnProcesser2()里看到

**Comment by donahowe** [comment]
微信群更新啦
