### ISSUE TITLE
需要 run.py 所需要的三个文件的连接

### ISSUE THREAD

**Issue by Frank-Y-Zheng** [donahowe/AutoStudio#37]
当我运行 run.py 时，缺少以下三个 Hugging Face 模型：

/data2/chengjunhao/THEATERGEN/pretrained_models/vae_ft_mse
/data2/chengjunhao/THEATERGEN/pretrained_models/diffusion_1.5_comic
/diffusion_1.5/unet
您能否提供这些模型或其权重的正确 Hugging Face 链接？此外，如果您能提供一个用于此设置的 Docker 容器，将不胜感激。

谢谢！

**Comment by LORDPQK** [comment]
https://huggingface.co/stabilityai/sd-vae-ft-mse
dreamlike-anime-1.0
dreamlike-anime-1.0/unet
兄弟 我复现的时候用的这三个可以，你试试，但我不知道为啥五轮对话生成之中，前两段对话每生产图片
