### ISSUE TITLE
SDXL下在默认的do_latent_guidance==True下结果是黑图

### ISSUE THREAD

**Issue by 15053285989** [donahowe/AutoStudio#40]
首先非常感谢分享这个项目
我在复现结果的时候, 发现sd1.5下可以生成图片, 但是在sdxl下生成的图都是黑的(同时没有异常),
如果把do_latent_guidance==False后就可以生成图片, 但是图片没有一致性了
请问这个是啥原因呢?

**Comment by yaospacetim** [comment]
我也发现了这个问题

**Comment by tangcan1600** [comment]
解决问题了吗
