### ISSUE TITLE
theatergen2

### ISSUE THREAD

**Issue by Fei-dong** [donahowe/AutoStudio#5]
theatergen2在[Theatergen](https://github.com/donahowe/Theatergen)的基础上做了什么修改呢

**Comment by donahowe** [comment]
你好！run.py有一些错误将autostudio打成了theatergen2，我已修改。确实AutoStudio是TheaterGen的续作。主要的改进点是：1.更加合理的自动生成bounding box, 2.角色交互性和画面的整体质量提升
