### ISSUE TITLE
Quality ..

### ISSUE THREAD

**Issue by Dreamlikec** [donahowe/AutoStudio#6]
Great job first, I download all the checkpoints your codes refer to, then do running this code, but I got some pictures like these... 

![img0_25step](https://github.com/donahowe/AutoStudio/assets/18510686/4f05b595-10cb-45ae-9097-284343dae2c1)
![t2_img0_25step](https://github.com/donahowe/AutoStudio/assets/18510686/0a153eee-5502-486b-8adf-7a644bcffbba)
![t3_img0_25step](https://github.com/donahowe/AutoStudio/assets/18510686/ef144d23-b714-4f23-adb3-d639876287ed)
![t4_img0_25step](https://github.com/donahowe/AutoStudio/assets/18510686/d26c5ab6-2cd9-4083-adf2-f87d564c6b73)
![t5_img0_25step](https://github.com/donahowe/AutoStudio/assets/18510686/f0f12791-24af-49f0-84ea-d041cf4ba703)

sd version is 1.5
ip-adapter version is ip-adapter-plus_sd15.bin

Can you give me some advise for above unsatisfactory results

**Comment by donahowe** [comment]
Sure, The likely causes of this issue are: too few DDIM steps and unreasonable bounding box settings. Possible solutions include: using a more detailed bounding box (including sub-ID bounding boxes) and trying a style transfer node that has been fine-tuned for a specific style, such as realistic or comic style (due to limited capabilities of SD 1.5 BASE).

**Comment by donahowe** [comment]
1.5 base checkpoint recommended: Disney, Dreamlike, Real

**Comment by Lne27** [comment]
Considering adjustments in parameters, it may be beneficial to try reducing the `fuse scale` or turning off `latent guidance` to potentially achieve higher-quality images for the sd1.5base model.

**Comment by dengfenglai321** [comment]
how do you run code to obtain the img above? only run run.py? but I can obtain the img

**Comment by donahowe** [comment]
Hello, I have fixed the bug. Please clone the repository again and configure the environment. Thank you for your attention.

**Comment by Dreamlikec** [comment]
> Hello, I have fixed the bug. Please clone the repository again and configure the environment. Thank you for your attention.


Thank you for your reply, I have no much experience in sd fine-tuned version from civitai, Could you recommend some XL version to me ?
