### ISSUE TITLE
run.py没有生成图片

### ISSUE THREAD

**Issue by dengfenglai321** [donahowe/AutoStudio#9]
你好，运行run.py只是生成Database如下图
![企业微信截图_17188769162635](https://github.com/donahowe/AutoStudio/assets/50360389/196aeb7f-8f11-4c32-b69b-3fc067bab05e)

./output/dialogue 1/turn 1/boxes.png
![企业微信截图_17188769717343](https://github.com/donahowe/AutoStudio/assets/50360389/fad4fe06-0b7a-45d9-8884-6aa11d6add81)

sd_path: runwayml/stable-diffusion-v1-5
vae_path: runwayml/stable-diffusion-v1-5/vae

请问怎么生成图片？

**Comment by donahowe** [comment]
您好，这是因为中间有报错了，可以把try语句去掉看看是哪里报错了

**Comment by donahowe** [comment]
Hello, I have fixed the bug. Please clone the repository again and configure the environment. Thank you for your attention.
